[theme]
base="dark"
backgroundColor="#0b110bff"
primaryColor="#1DB954"
secondaryBackgroundColor="#457e59"
#dataframeHeaderBackgroundColor="#32CD32"
codeBackgroundColor="#457e59"
textColor="#e1ece3"
font="sans-serif"

[theme.sidebar]
primaryColor="#32CD32"
backgroundColor="#17271bff"
secondaryBackgroundColor="#2a4f34ff"
textColor="#e1ece3"

[server]
runOnSave = true

# black="#0f1f0fff"
# blackgreen="#002918ff"
# lightgrey="#a8b2a8"
# offwhite="#e1ece3"
# darkgreen="#0d5637ff"
# midgreen="#457e59"
# lightgreen="#62d089"
# spotgreen="#1ed760"
# backgroundColor="#909f92ff"
# secondaryBackgroundColor="#2a4f34ff"
